// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBqKryHwZ935kuGLoqaXYWc8z0GUYib4',
    appId: '1:292895635239:web:0e56c8a746bf1793051b02',
    messagingSenderId: '292895635239',
    projectId: 'charity-app-7c587',
    authDomain: 'charity-app-7c587.firebaseapp.com',
    storageBucket: 'charity-app-7c587.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwtadbzhIBKPEefvLLKvQ4dsS2cBFBCI',
    appId: '1:292895635239:android:6b700f1443a0ac89051b02',
    messagingSenderId: '292895635239',
    projectId: 'charity-app-7c587',
    storageBucket: 'charity-app-7c587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo2nyFHDX6VoThtKMDOjjdoYN2JeVDq-o',
    appId: '1:292895635239:ios:24adf562aea10195051b02',
    messagingSenderId: '292895635239',
    projectId: 'charity-app-7c587',
    storageBucket: 'charity-app-7c587.firebasestorage.app',
    iosClientId: '292895635239-rkumfch79b4vmph6h930qrffpsan4u67.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo2nyFHDX6VoThtKMDOjjdoYN2JeVDq-o',
    appId: '1:292895635239:ios:24adf562aea10195051b02',
    messagingSenderId: '292895635239',
    projectId: 'charity-app-7c587',
    storageBucket: 'charity-app-7c587.firebasestorage.app',
    iosClientId: '292895635239-rkumfch79b4vmph6h930qrffpsan4u67.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzBqKryHwZ935kuGLoqaXYWc8z0GUYib4',
    appId: '1:292895635239:web:bfa1b89bec54c640051b02',
    messagingSenderId: '292895635239',
    projectId: 'charity-app-7c587',
    authDomain: 'charity-app-7c587.firebaseapp.com',
    storageBucket: 'charity-app-7c587.firebasestorage.app',
  );

}